#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyparsing
Version  : 3.0.8
Release  : 98
URL      : https://files.pythonhosted.org/packages/31/df/789bd0556e65cf931a5b87b603fcf02f79ff04d5379f3063588faaf9c1e4/pyparsing-3.0.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/31/df/789bd0556e65cf931a5b87b603fcf02f79ff04d5379f3063588faaf9c1e4/pyparsing-3.0.8.tar.gz
Summary  : pyparsing module - Classes and methods to define and execute parsing grammars
Group    : Development/Tools
License  : MIT
Requires: pypi-pyparsing-license = %{version}-%{release}
Requires: pypi-pyparsing-python = %{version}-%{release}
Requires: pypi-pyparsing-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : py
BuildRequires : pypi(flit_core)
BuildRequires : pytest

%description
PyParsing -- A Python Parsing Module
====================================
|Build Status| |Coverage|

%package license
Summary: license components for the pypi-pyparsing package.
Group: Default

%description license
license components for the pypi-pyparsing package.


%package python
Summary: python components for the pypi-pyparsing package.
Group: Default
Requires: pypi-pyparsing-python3 = %{version}-%{release}

%description python
python components for the pypi-pyparsing package.


%package python3
Summary: python3 components for the pypi-pyparsing package.
Group: Default
Requires: python3-core
Provides: pypi(pyparsing)

%description python3
python3 components for the pypi-pyparsing package.


%prep
%setup -q -n pyparsing-3.0.8
cd %{_builddir}/pyparsing-3.0.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650139187
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyparsing
cp %{_builddir}/pyparsing-3.0.8/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pyparsing/df156c6a0a89ed2a3bd4a473c68cf85907509ca0
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyparsing/df156c6a0a89ed2a3bd4a473c68cf85907509ca0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
